package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ProductionBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ProductionBuild")) {
    requirements {
        add {
            equals("system.agent.name", "Windows Server 2019 (AWS)")
        }
    }
}
